/**
 * Build script for Vercel deployment.
 * Generates env.local.js from Vercel environment variables.
 *
 * Set these in your Vercel project settings (Settings > Environment Variables):
 *   GITHUB_TOKEN     - GitHub Personal Access Token
 *   GITHUB_USERNAME  - Your GitHub username
 *   REPO_OWNER       - Target repo owner  (default: Thomas-nada)
 *   REPO_NAME        - Target repo name   (default: cap)
 */

const fs = require('fs');
const path = require('path');

const token    = process.env.GITHUB_TOKEN    || '';
const username = process.env.GITHUB_USERNAME || '';
const owner    = process.env.REPO_OWNER      || 'Thomas-nada';
const repo     = process.env.REPO_NAME       || 'cap';

const content = `// Auto-generated by scripts/build-env.js — do not edit
export const ENV = {
    GITHUB_TOKEN: "${token}",
    GITHUB_USERNAME: "${username}",
    REPO_OWNER: "${owner}",
    REPO_NAME: "${repo}",
};
`;

const outPath = path.join(__dirname, '..', 'env.local.js');
fs.writeFileSync(outPath, content, 'utf-8');
console.log('Generated env.local.js for deployment');
